git:
  depth: 10

language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '8'
  - '10'
  - '12'

install:
  - npm ci

script:
  - npm run build
  - npm run test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
