git:
  depth: 10

language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '10'
  - '12'
  - '14'

install:
  - npm ci

script:
  - npm run test
  - npm run build

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
