name: Prefix reminder

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: remind-about-prefixes
      uses: github-actions-up-and-running/pr-comment@v1.0.0
      with:
        message: "Did you remember to add changeset to `@zazuko/prefixes`?"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
